#ifndef SOP_GROUPASATTR_GLOBAL_H
#define SOP_GROUPASATTR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOP_GROUPASATTR_LIBRARY)
#  define SOP_GROUPASATTRSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOP_GROUPASATTRSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOP_GROUPASATTR_GLOBAL_H
